/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import javax.swing.AbstractListModel;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.ListModel;
import javax.swing.table.TableModel;
import presenter.Presenter;
import presenter.IPresenter;
import utils.ViewModeUtils;

/**
 *
 * @author Luis
 */
public class View extends javax.swing.JFrame implements IView {

    /**
     * Creates new form MainFrame
     */
    
    private int xx;
    private int yy;
    private int x;
    private int y;
    private String viewMode;
    private IPresenter presenter;
    
    public View() {
        viewMode = ViewModeUtils.getDefaultViewMode();
        initComponents();
        createRowHeader();
        presenter = new Presenter(this);
        presenter.setTableModel();
    }

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        subtitleLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        exitLabel = new javax.swing.JLabel();
        sheetLabel = new javax.swing.JLabel();
        optionsLabel = new javax.swing.JLabel();
        redoLabel = new javax.swing.JLabel();
        undoLabel = new javax.swing.JLabel();
        viewModeLabel = new javax.swing.JLabel();
        recordMacroButton = new javax.swing.JLabel();
        playMacroButton = new javax.swing.JLabel();
        homePanel = new javax.swing.JPanel();
        sheetPanel = new javax.swing.JPanel();
        tableScrollPane = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        optionsPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setUndecorated(true);

        headerPanel.setBackground(new java.awt.Color(1, 198, 83));
        headerPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                onHeaderDragged(evt);
            }
        });
        headerPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                onHeaderPressed(evt);
            }
        });
        headerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        subtitleLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        subtitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        subtitleLabel.setText("ExcelSaga");
        subtitleLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        headerPanel.add(subtitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 22, -1, -1));

        titleLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setText("The most powerful app out there");
        titleLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        headerPanel.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 77, -1, -1));

        exitLabel.setBackground(new java.awt.Color(1, 198, 83));
        exitLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        exitLabel.setForeground(new java.awt.Color(255, 255, 255));
        exitLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitLabel.setText("X");
        exitLabel.setOpaque(true);
        exitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onExitClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                onExitPressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                onExitReleased(evt);
            }
        });
        headerPanel.add(exitLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(835, 0, 37, -1));

        sheetLabel.setBackground(new java.awt.Color(0, 150, 62));
        sheetLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sheetLabel.setForeground(new java.awt.Color(255, 255, 255));
        sheetLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sheetLabel.setText("Sheet");
        sheetLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sheetLabel.setMaximumSize(new java.awt.Dimension(49, 20));
        sheetLabel.setMinimumSize(new java.awt.Dimension(49, 20));
        sheetLabel.setOpaque(true);
        sheetLabel.setPreferredSize(new java.awt.Dimension(49, 20));
        sheetLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onSheetClicked(evt);
            }
        });
        headerPanel.add(sheetLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 149, 140, 30));

        optionsLabel.setBackground(new java.awt.Color(1, 198, 83));
        optionsLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        optionsLabel.setForeground(new java.awt.Color(255, 255, 255));
        optionsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        optionsLabel.setText("Options");
        optionsLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        optionsLabel.setOpaque(true);
        optionsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onOptionsClicked(evt);
            }
        });
        headerPanel.add(optionsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 140, 30));

        redoLabel.setBackground(new java.awt.Color(1, 198, 83));
        redoLabel.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        redoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        redoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/Redo_32px.png"))); // NOI18N
        redoLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        redoLabel.setOpaque(true);
        redoLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onRedoClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                onRedoPressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                onRedoReleased(evt);
            }
        });
        headerPanel.add(redoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 150, 30, 30));

        undoLabel.setBackground(new java.awt.Color(1, 198, 83));
        undoLabel.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        undoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        undoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/Undo_32px.png"))); // NOI18N
        undoLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        undoLabel.setOpaque(true);
        undoLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onUndoClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                onUndoPressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                onUndoReleased(evt);
            }
        });
        headerPanel.add(undoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 150, 30, 30));

        viewModeLabel.setBackground(new java.awt.Color(1, 198, 83));
        viewModeLabel.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        viewModeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewModeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/Eye_32px.png"))); // NOI18N
        viewModeLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        viewModeLabel.setOpaque(true);
        viewModeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onViewModeClicked(evt);
            }
        });
        headerPanel.add(viewModeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 150, 30, 30));

        recordMacroButton.setBackground(new java.awt.Color(1, 198, 83));
        recordMacroButton.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        recordMacroButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        recordMacroButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/Record_32px.png"))); // NOI18N
        recordMacroButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        recordMacroButton.setOpaque(true);
        recordMacroButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onRecordMacroClicked(evt);
            }
        });
        headerPanel.add(recordMacroButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 150, 30, 30));

        playMacroButton.setBackground(new java.awt.Color(1, 198, 83));
        playMacroButton.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        playMacroButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        playMacroButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/Circled Play_32px.png"))); // NOI18N
        playMacroButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        playMacroButton.setOpaque(true);
        playMacroButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onPlayMacroClicked(evt);
            }
        });
        headerPanel.add(playMacroButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 150, 30, 30));

        homePanel.setBackground(new java.awt.Color(255, 255, 255));
        homePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 198, 83), 2));
        homePanel.setLayout(new java.awt.CardLayout());

        sheetPanel.setLayout(new javax.swing.BoxLayout(sheetPanel, javax.swing.BoxLayout.LINE_AXIS));

        table.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        table.setForeground(new java.awt.Color(51, 51, 51));
        table.setCellSelectionEnabled(true);
        table.setName(""); // NOI18N
        table.setRowHeight(28);
        table.setSelectionBackground(new java.awt.Color(51, 153, 255));
        table.getTableHeader().setReorderingAllowed(false);
        tableScrollPane.setViewportView(table);

        sheetPanel.add(tableScrollPane);

        homePanel.add(sheetPanel, "card2");

        javax.swing.GroupLayout optionsPanelLayout = new javax.swing.GroupLayout(optionsPanel);
        optionsPanel.setLayout(optionsPanelLayout);
        optionsPanelLayout.setHorizontalGroup(
            optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        optionsPanelLayout.setVerticalGroup(
            optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        homePanel.add(optionsPanel, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(homePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onExitClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onExitClicked
        presenter.onExitClicked();
    }//GEN-LAST:event_onExitClicked

    private void onSheetClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onSheetClicked
        presenter.onSheetClicked();
    }//GEN-LAST:event_onSheetClicked

    private void onOptionsClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onOptionsClicked
        presenter.onOptionsClicked();
    }//GEN-LAST:event_onOptionsClicked

    private void onHeaderPressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onHeaderPressed
        presenter.onHeaderPressed(evt.getX(), evt.getY());
    }//GEN-LAST:event_onHeaderPressed

    private void onHeaderDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onHeaderDragged
        presenter.onHeaderDragged(evt.getXOnScreen(), evt.getYOnScreen());
    }//GEN-LAST:event_onHeaderDragged

    private void onExitPressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onExitPressed
        presenter.onExitPressed();
    }//GEN-LAST:event_onExitPressed

    private void onExitReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onExitReleased
        presenter.onExitReleased();
    }//GEN-LAST:event_onExitReleased

    private void onViewModeClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onViewModeClicked
        presenter.onViewModeClicked(viewMode);
    }//GEN-LAST:event_onViewModeClicked

    private void onRedoPressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onRedoPressed
        presenter.onRedoPressed();
    }//GEN-LAST:event_onRedoPressed

    private void onRedoReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onRedoReleased
        presenter.onRedoReleased();
    }//GEN-LAST:event_onRedoReleased

    private void onUndoPressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onUndoPressed
        presenter.onUndoPressed();
    }//GEN-LAST:event_onUndoPressed

    private void onUndoReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onUndoReleased
        presenter.onUndoReleased();
    }//GEN-LAST:event_onUndoReleased

    private void onPlayMacroClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onPlayMacroClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_onPlayMacroClicked

    private void onRecordMacroClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onRecordMacroClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_onRecordMacroClicked

    private void onUndoClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onUndoClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_onUndoClicked

    private void onRedoClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onRedoClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_onRedoClicked

    @Override
    public void setTableModel(TableModel tableModel) {
        table.setModel(tableModel);
    }
    
    @Override
    public void setViewMode(String viewMode){
        this.viewMode = viewMode;
    }
    
    @Override
    public void setViewModeColor() {
        viewModeLabel.setBackground(new Color(0, 150, 62));
    }

    @Override
    public void resetViewModeColor() {
        viewModeLabel.setBackground(new Color(1, 198, 83));
    }
    
    @Override
    public void exitSystem() {
        System.exit(0);
    }

    @Override
    public void setExitColor() {
        exitLabel.setBackground(new Color(0, 150, 62));
    }

    @Override
    public void resetExitColor() {
        exitLabel.setBackground(new Color(1, 198, 83));
    }
    
    @Override
    public void setRedoColor() {
        redoLabel.setBackground(new Color(0, 150, 62));
    }

    @Override
    public void resetRedoColor() {
        redoLabel.setBackground(new Color(1, 198, 83));
    }

    @Override
    public void setUndoColor() {
        undoLabel.setBackground(new Color(0, 150, 62));
    }

    @Override
    public void resetUndoColor() {
        undoLabel.setBackground(new Color(1, 198, 83));
    }

    @Override
    public void ShowSheetPanel() {
        sheetPanel.setVisible(true);
    }

    @Override
    public void hideSheetPanel() {
        sheetPanel.setVisible(false);
    }

    @Override
    public void setSheetColor() {
        sheetLabel.setBackground(new Color(0, 150, 62));
    }

    @Override
    public void resetSheetColor() {
        sheetLabel.setBackground(new Color(1, 198, 83));
    }

    @Override
    public void ShowOptionsPanel() {
        optionsPanel.setVisible(true);
    }

    @Override
    public void hideOptionsPanel() {
        optionsPanel.setVisible(false);
    }

    @Override
    public void setOptionsColor() {
        optionsLabel.setBackground(new Color(0, 150, 62));
    }

    @Override
    public void resetOptionsColor() {
        optionsLabel.setBackground(new Color(1, 198, 83));
    }

    @Override
    public void setWindowPressedCoordinates(int x, int y) {
        xx = x;
        yy = y;
    }

    @Override
    public void setWindowDraggedCoordinates(int x, int y) {
        this.x = x;
        this.y = y;
    }

    @Override
    public void setWindowLocation(int x, int y) {
        
        this.setLocation(x, y);
    }
    
    @Override
    public int getXX() {
        return xx;
    }

    @Override
    public int getYY() {
        return yy;
    }

    @Override
    public int getX() {
        return x;
    }

    @Override
    public int getY() {
        return y;
    }
    
    private void createRowHeader(){
        
        ListModel lm = new AbstractListModel() {
            String headers[] = {"1", "2", "3", "4", "5", "6", "7", "8", "9", "10"};

            public int getSize() {
              return headers.length;
            }

            @Override
            public Object getElementAt(int index) {
              return headers[index];
            }
          };
        
        JList rowHeader = new JList(lm);
        rowHeader.setFixedCellWidth(50);
        rowHeader.setFixedCellHeight(table.getRowHeight());
        rowHeader.setCellRenderer(new RowHeaderRenderer(table));
        rowHeader.setBackground(new Color(255, 255, 255));
        rowHeader.setOpaque(true);
        tableScrollPane.setRowHeaderView(rowHeader);
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new View().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exitLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel optionsLabel;
    private javax.swing.JPanel optionsPanel;
    private javax.swing.JLabel playMacroButton;
    private javax.swing.JLabel recordMacroButton;
    private javax.swing.JLabel redoLabel;
    private javax.swing.JLabel sheetLabel;
    private javax.swing.JPanel sheetPanel;
    private javax.swing.JLabel subtitleLabel;
    private javax.swing.JTable table;
    private javax.swing.JScrollPane tableScrollPane;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel undoLabel;
    private javax.swing.JLabel viewModeLabel;
    // End of variables declaration//GEN-END:variables


}
